name: Scrape Football Events

on:
  schedule:
    - cron: '0 * * * *' # Jalankan setiap jam (UTC)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Timezone to WIB
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Jakarta"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      - name: Verify Chrome and Chromedriver
        run: |
          google-chrome --version
          chromedriver --version
          if ! command -v chromedriver; then
            echo "Chromedriver tidak terinstal"
            exit 1
          fi
          if ! command -v google-chrome; then
            echo "Google Chrome tidak terinstal"
            exit 1
          fi

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 selenium fuzzywuzzy python-dateutil tenacity pytz requests python-Levenshtein

      - name: Ensure french_dict.json
        run: |
          if [ ! -f french_dict.json ]; then
            echo "french_dict.json tidak ditemukan, pastikan sudah di-commit ke repository"
            exit 1
          fi

      - name: Ensure manual_schedule.json
        run: |
          if [ ! -f manual_schedule.json ]; then
            echo "[]" > manual_schedule.json
            echo "manual_schedule.json dibuat dengan konten kosong"
          fi

      - name: Run Scrape Script
        run: python scraper/scrape_events.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add event.json manual_schedule.json
          git diff --cached --quiet || (git commit -m "Update event.json and manual_schedule.json" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}