name: Scrape Players

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    # timeout-minutes: 15   Add timeout

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set WIB Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Jakarta"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chromedriver@v1
        with:
          chrome-version: 'latest'
          check-latest: true

      - name: Verify Chrome and ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 selenium fuzzywuzzy python-Levenshtein python-dateutil tenacity pytz

      - name: Ensure required files exist
        run: |
          if [ ! -f french_dict.json ]; then
            echo '{"leagues": {}, "teams": {"ES Tunis": "Esperance Tunis", "Esperance Sportive de Tunis": "Esperance Tunis", "Chelsea FC": "Chelsea"}}' > french_dict.json
          fi
          if [ ! -f manual_schedule.json ]; then
            echo "[]" > manual_schedule.json
          fi

      - name: Run Scraper
        run: |
          export DISPLAY=:0
          python scraper/scrape_events.py
        env:
          PYTHONUNBUFFERED: 1

      - name: Commit Changes
        if: success()
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "actions@github.com"
          git add *.json *.html
          git diff --cached --quiet || (git commit -m "Update schedules and caches [skip ci]" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}