name: Scrape Players

on:
  schedule:
    - cron: '30 16 * * *' # Per jam
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set WIB Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Jakarta"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'
          install-chromedriver: true

      - name: Verify Chrome and ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version
          if ! command -v chromedriver; then exit 1; fi
          if ! command -v google-chrome; then exit 1; fi

      - name: Clean up existing Chrome and ChromeDriver processes
        run: |
          pkill -9 chromedriver || true
          pkill -9 google-chrome || true
          sleep 2
          if pgrep chromedriver || pgrep google-chrome; then
            echo "Warning: Some Chrome/ChromeDriver processes may still be running"
            pgrep -l chromedriver || true
            pgrep -l google-chrome || true
          else
            echo "Chrome and ChromeDriver processes cleaned up successfully"
          fi

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 selenium fuzzywuzzy python-Levenshtein python-dateutil tenacity pytz

      - name: Ensure french_dict.json
        run: |
          if [ ! -f french_dict.json ]; then
            echo '{"leagues": {}, "teams": {"ES Tunis": "Esperance Tunis", "Esperance Sportive de Tunis": "Esperance Tunis", "Chelsea FC": "Chelsea"}}' > french_dict.json
          fi

      - name: Ensure manual_schedule.json
        run: |
          if [ ! -f manual_schedule.json ]; then
            echo "[]" > manual_schedule.json
          fi

      - name: Run Scraper
        run: python scraper/scrape_events.py

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "actions@github.com"
          git add *.json *.html
          git diff --cached --quiet || (git commit -m "Update schedules and caches" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
